### ISSUE TITLE
Fennec is broken

### ISSUE THREAD

**Issue by OctoNezd** [sfX-android/android_vendor_extendrom#13]
Launching Fennec installed into /system/app throws this for me:
```
01-09 19:45:12.826 14949 14970 E GeckoLibLoad: Load sqlite start
01-09 19:45:12.826 14949 14970 E GeckoLibLoad: Couldn't get a handle to libnss3!
01-09 19:45:12.826 14949 14970 E GeckoLibLoad: Throw
01-09 19:45:12.826 14949 14970 E GeckoLibLoad: Load sqlite done
01-09 19:45:12.827 14949 14970 E AndroidRuntime: FATAL EXCEPTION: Gecko
01-09 19:45:12.827 14949 14970 E AndroidRuntime: Process: org.mozilla.fennec_fdroid, PID: 14949
01-09 19:45:12.827 14949 14970 E AndroidRuntime: java.lang.Exception: Error loading sqlite libraries
01-09 19:45:12.827 14949 14970 E AndroidRuntime:        at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
01-09 19:45:12.827 14949 14970 E AndroidRuntime:        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:106)
01-09 19:45:12.827 14949 14970 E ExceptionHandler: Uncaught exception handled:
01-09 19:45:12.827 14949 14970 E ExceptionHandler: java.lang.Exception: Error loading sqlite libraries
01-09 19:45:12.827 14949 14970 E ExceptionHandler:      at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
01-09 19:45:12.827 14949 14970 E ExceptionHandler:      at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:106)
01-09 19:45:12.828 14949 14970 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1641746712827, throwable=java.lang.Exception: Error loading sqlite libraries, breadcrumbs=[], uuid=e3e9c4dd-927c-47d8-8063-2527d2aeb6f9)
```

Removing it from system and installing it manually through f-droid makes it work fine however.

**Comment by OctoNezd** [comment]
also almost immediately after that I see this:
```
01-09 19:45:13.136  3407  3917 W MediaProvider: Failed to fetch original file descriptor
01-09 19:45:13.136  3407  3917 W MediaProvider: java.io.IOException: stat failed: EACCES (Permission denied)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at com.android.providers.media.MediaProvider.getFileFromFileDescriptor(MediaProvider.java:5794)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at com.android.providers.media.MediaProvider.getOriginalMediaFormatFileDescriptor(MediaProvider.java:5711)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at com.android.providers.media.MediaProvider.openTypedAssetFileCommon(MediaProvider.java:7134)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at com.android.providers.media.MediaProvider.openTypedAssetFile(MediaProvider.java:7115)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:548)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at android.os.Binder.execTransactInternal(Binder.java:1184)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at android.os.Binder.execTransact(Binder.java:1143)
01-09 19:45:13.136  3407  3917 W MediaProvider: Caused by: android.system.ErrnoException: stat failed: EACCES (Permission denied)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at libcore.io.Linux.stat(Native Method)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at libcore.io.ForwardingOs.stat(ForwardingOs.java:853)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:420)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at libcore.io.ForwardingOs.stat(ForwardingOs.java:853)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at android.app.ActivityThread$AndroidOs.stat(ActivityThread.java:7739)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at android.system.Os.stat(Os.java:919)
01-09 19:45:13.136  3407  3917 W MediaProvider:         at com.android.providers.media.MediaProvider.getFileFromFileDescriptor(MediaProvider.java:5788)
01-09 19:45:13.136  3407  3917 W MediaProvider:         ... 7 more
```

**Comment by OctoNezd** [comment]
On manual install I see more files compared to extendrom inclusion in Fennec folder:
```
/data/app/~~jnqPMDoDHaBxS7k72bvvbg==/org.mozilla.fennec_fdroid-kDG0zn7WKS0Hx9XeEts2Gw==: ls
total 72672
drwxrwxr-x 4 1000 1000     3488 2022-01-09 17:30 .
drwxrwxr-x 3 1000 1000     3488 2022-01-09 17:30 ..
-rw-r--r-- 1 1000 1000 74326867 2022-01-09 17:30 base.apk
drwxr-xr-x 3 1000 1000     3488 2022-01-09 17:30 lib
drwxrwx--x 3 1000 1012     3488 2022-01-09 17:30 oat
```

**Comment by steadfasterX** [comment]
should be "fixed" (worarounded) by https://github.com/sfX-android/android_vendor_extendrom/commit/6bf9d6ec5fe5857359a19a5efa3b8f287f52cf29
